Repository Marius-P1/Need4Stek, pull requests merged in 2023-04, with the labels that each got.

#12 6 create the repository structure
  .github/workflows/chocolatine.yml
  .github/workflows/discord.yaml
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  bonus/.gitkeep
  include/lib.h
  include/nfs.h
  lib/my/Makefile
  lib/my/my_arraycpy.c
  lib/my/my_arraylen.c
  lib/my/my_atoi.c
  lib/my/my_cleanstr.c
  lib/my/my_put_nbr.c
  lib/my/my_putchar.c
  lib/my/my_putstr.c
  lib/my/my_str_isalphanum.c
  lib/my/my_str_to_word_array.c
  lib/my/my_str_to_word_array2.c
  lib/my/my_strcat.c
  lib/my/my_strcmp.c
  lib/my/my_strcpy.c
  lib/my/my_strkcpy.c
  lib/my/my_strlen.c
  lib/my/my_strncat.c
  lib/my/my_strncmp.c
  src/project_base/error_handling_args.c
  src/project_base/help_display.c
  src/project_base/main.c
  src/project_base/needforstek.c
  tests/test_display_help.c
  tests/test_handling_args.c
Labels: Documentation, Enhancement, Structure

#19 :bento: Create bonus map
  bonus/map/Bonus_map_with_z_angle.ttt
Labels: Tests, Utility

#20 :sparkles: Added the biggest ia ever
  Makefile
  include/nfs.h
  include/nfs_returns.h
  src/car_movements/car_forward_backward.c
  src/car_movements/car_wheels_movements.c
  src/control_car/control_loop.c
  src/control_car/get_control.c
  src/get_current_infos/get_lidar_infos.c
  src/get_current_infos/get_no_error_infos.c
  src/project_base/needforstek.c
Labels: Enhancement
